#!/bin/sh

./test_blas2s < $CBLAPACKDIR/test/input/sblat2.in &&
./test_blas2d < $CBLAPACKDIR/test/input/dblat2.in &&
./test_blas2c < $CBLAPACKDIR/test/input/cblat2.in &&
./test_blas2z < $CBLAPACKDIR/test/input/zblat2.in &&
exit 0
exit 2
